version: '3.9'

services:
  # Aplicação Laravel
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: suppliers_api_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - suppliers_network
    depends_on:
      - mysql
      - redis

  # Servidor Web Nginx
  nginx:
    image: nginx:alpine
    container_name: suppliers_api_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - suppliers_network
    depends_on:
      - app

  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: suppliers_api_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: suppliers_api
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: password
      MYSQL_USER: laravel
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - suppliers_network

  # Cache Redis
  redis:
    image: redis:alpine
    container_name: suppliers_api_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - suppliers_network

  # phpMyAdmin para gerenciar o banco
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: suppliers_api_phpmyadmin
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - suppliers_network
    depends_on:
      - mysql

  # Redis Commander para gerenciar o cache
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: suppliers_api_redis_commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    networks:
      - suppliers_network
    depends_on:
      - redis

networks:
  suppliers_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: